title: paul356's Blog
description: Personal Thoughts on Technology and Related
theme: just-the-docs

url: https://paul356.github.io

aux_links:
  paul356's Github: https://github.com/paul356

just_the_docs:
    collections:
        posts:
            name: Posts


plugins:
    - jekyll-feed
